{{- $namespaces := .Values.namespaces }}
{{- range $i, $app := $namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ $app.name }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ $app.namespace }}
    server: https://kubernetes.default.svc
  project: tenant-namespaces
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: main
    #path: charts/{{ $app.chart }}
    path: charts/namespaces
    helm:
      values: |
{{ toYaml $app.values | indent 8 }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
