apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  creationTimestamp: null
  name: project-request
  namespace: openshift-config
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
# Dynamic group binding - the group from the sync is name projectname
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: "${PROJECT_NAME}-admins"
    namespace: "${PROJECT_NAME}"
  subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "${PROJECT_NAME}-admins"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: customer-admin
# Denies all pod -> pod communication between namespaces
- kind: NetworkPolicy
  apiVersion: networking.k8s.io/v1
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: deny-by-default
    namespace: ${PROJECT_NAME}
  spec:
    podSelector: {}
    ingress: []
# Only allow connections from the OpenShift Container Platform Ingress Controller
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: allow-from-openshift-ingress
    namespace: ${PROJECT_NAME}
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            policy-group.network.openshift.io/ingress: ""
    podSelector: {}
    policyTypes:
    - Ingress
# Only accept connections from pods within a project
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: allow-same-namespace
    namespace: ${PROJECT_NAME}
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
# default resourceQuota per project (namspeace scoped)
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: defualt-resourcequota
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      limits.cpu: 8
      limits.memory: 8Gi
      requests.cpu: 4
      requests.memory: 4Gi
# default limitrange per project (workload scoped individual containers / pods)
- apiVersion: v1
  kind: LimitRange
  metadata:
    labels:
      {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
    name: default-limitrange
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 125m
        memory: 128Mi
      max:
        cpu: 1000m
        memory: 1024Mi
    - type: Pod
      max:
        cpu: 1000m
        memory: 4096Mi
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
