apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app-1
  name: test-app-1
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app-1
  type: ClusterIP
