apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: test-app-1
  name: test-app-1
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: 8080-8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-app-1
    weight: 100
  wildcardPolicy: None
