#dependencies:
#  - name: helper-status-checker
#    repository: https://abavage.github.io/helm-gitops/
#    version: 4.0.10

apiVersion: v2
name: openshift-aap
description: Deploy OpenShift AAP
type: application
version: 0.0.11
