dependencies:
  - name: helper-status-checker
    repository: file://../helper-status-checker
    version: 4.0.10

apiVersion: v2
name: openshift-pipelines
description: Openshift pipelines operator
version: 0.0.1
