helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: openshift-pipelines-operator
      subscriptionName: openshift-pipelines-operator
      namespace:
        name: openshift-operators
      serviceAccount:
        name: "status-checker"


csv: ""
