{{- $controllers := .Values.ingresscontroller }}
{{- if .Values.infrastructure }}
{{- range .Values.infrastructure }}
{{- if eq .chart "openshift-ingress" }}
{{- if .values.ingresscontroller }}
{{- $controllers = .values.ingresscontroller }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $controllers }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ingresscontroller-{{ .name }}-certificate
  namespace: openshift-ingress
spec:
  secretName: ingresscontroller-{{ .name }}-certificate
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - "{{ .certificateCommonName }}"
  duration: 1080h
  renewBefore: 540h
  usages:
    - "server auth"
    - "client auth"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
{{- end }}
