{{- $controllers := .Values.ingresscontroller }}
{{- if .Values.infrastructure }}
{{- range .Values.infrastructure }}
{{- if eq .chart "openshift-ingress" }}
{{- if .values.ingresscontroller }}
{{- $controllers = .values.ingresscontroller }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $controllers }}
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    ingress.operator.openshift.io/auto-delete-load-balancer: "true"
  labels:
    custom.ingresscontroller: "true"
  name: {{ .name }}
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: ingresscontroller-{{ .name }}-certificate
  domain: {{ .domain }}
  endpointPublishingStrategy:
    loadBalancer:
      dnsManagementPolicy: Unmanaged
      providerParameters:
        aws:
          networkLoadBalancer: {}
          type: NLB
        type: AWS
      scope: {{ .scope }}
    type: LoadBalancerService
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null
  namespaceSelector:
    matchLabels:
      ingress: {{ .name }}
{{- end }}
