{{- range .Values.ingresscontroller }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ingresscontroller-{{ .name }}-certificate
  namespace: openshift-ingress
  labels:
    ingresscontroller: {{ .name }}
type: Opaque
data:
  tls.crt: {{ .tls_crt }}
  tls.key: {{ .tls_key }}
{{- end }}
