helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: aws-efs-csi-driver-operator
      subscriptionName: aws-efs-csi-driver-operator
      namespace:
        name: openshift-cluster-csi-drivers
      serviceAccount:
        name: "status-checker"

csv: ""
roleArn: ""
fileSystemId: ""

