apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
  {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
  name: allow-from-openshift-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
      matchLabels:
      policy-group.network.openshift.io/ingress: ""
  podSelector: {}
  policyTypes:
  - Ingress