apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
  name: allow-same-namespace
  namespace: ${PROJECT_NAME}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}