apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    {{ .Values.custom_label.key }}: {{ .Values.custom_label.value }}
   name: default-resourcequota
   namespace: {{ .Values.namespace }}
spec:
  hard:
    limits.cpu: {{ .Values.resourcequota.limits_cpu }}
    limits.memory: {{ .Values.resourcequota.limits_memory }}
    requests.cpu: {{ .Values.resourcequota.requests_cpu }}
    requests.memory: {{ .Values.resourcequota.requests_memory }}