ingresscontroller:
  - name: "dummy"
    scope: "dummy"
    domain: "dummy"
    #tls_crt: "dummy"
    #tls_key: "dummy"
    # wildcard fqdn for the cert -- *.mydomain.int
    certificateCommonName: "dummy"

