apiVersion: oadp.openshift.io/v1alpha1
kind: CloudStorage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ .Values.clustername }}-aap
  namespace: openshift-adp
spec:
  creationSecret:
    key: credentials
    name: cloud-credentials
  enableSharedConfig: true
  name: {{ .Values.clustername }}-{{ .Values.bucketname }}
  provider: aws
  region: {{ .Values.region }}