apiVersion: oadp.openshift.io/v1alpha1
kind: CloudStorage
metadata:
 name: {{ .Values.clustername }}-aap
 namespace: openshift-adp
 annotations:
   argocd.argoproj.io/sync-wave: "1"
   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
 creationSecret:
   key: credentials
   name: cloud-credentials
 enableSharedConfig: true
 name: {{ .Values.clustername }}-{{ .Values.bucketname }}
 provider: aws
 region: {{ .Values.region }}