apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
 name: {{ .Values.clustername }}-aap
 namespace: openshift-adp
 annotations:
   argocd.argoproj.io/sync-wave: "3"
   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
 backupImages: true
 features:
   #dataMover:
   #  enable: false
 backupLocations:
 - bucket:
     cloudStorageRef:
       name: {{ .Values.clustername }}-aap
     credential:
       key: credentials
       name: cloud-credentials
     prefix: velero
     default: true
     config:
       region: {{ .Values.region }}
 configuration:
   velero:
     defaultPlugins:
     - openshift
     - aws
     - csi
   nodeAgent:
     enable: true
     uploaderType: kopia
