apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "openshift-adp"
  labels:
    kubernetes.io/metadata.name: openshift-adp
  name: openshift-adp