# oc get externalsecrets.operator.openshift.io/cluster  -o yaml
apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecrets
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: external-secrets-operator
  name: cluster
spec: {}
