apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    operators.coreos.com/openshift-external-secrets-operator.external-secrets-operator: ""
  name: openshift-external-secrets-operator
  namespace: external-secrets-operator
spec:
  channel: {{ .Values.channel }}
  config:
    env:
    - name: ROLEARN
      value: no-arn-needed
  installPlanApproval: Manual
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.csv }}
