---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
  labels:
  name: operator-install-job-hook
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
  labels:
  name: operator-install-job-hook
  namespace: openshift-gitops-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-install-job-hook
subjects:
- kind: ServiceAccount
  name: operator-install-job-hook
  namespace: openshift-gitops-operator
---
apiVersion: v1
imagePullSecrets:
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  name: operator-install-job-hook
  namespace: openshift-gitops-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
  name: operator-install-job-hook
  namespace: openshift-gitops-operator
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: operator-install-job-hook
      serviceAccountName: operator-install-job-hook
      terminationGracePeriodSeconds: 30
      containers:
        - name: operator-install-job-hook
          image: "{{ .Values.defaultImage }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: SLEEP
            value: "30"
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              echo "Starting OpenShift GitOps Operator"

              SLEEP=5

              CSV_STATUS="Pending"
              MAX_RETRIES=60
              attempt=1

              while [[ "$CSV_STATUS" != "InstallSucceeded" ]]; do
                # Find the CSV name matching openshift-gitops-operator
                CSV_NAME=$(oc get csv -n openshift-gitops-operator | grep openshift-gitops-operator| awk '{print $1}')

                if [[ -z "$CSV_NAME" ]]; then
                  echo "CSV not found yet. Waiting... ($attempt/$MAX_RETRIES)"
                else
                  # Get the CSV status.reason safely
                  CSV_STATUS=$(oc get csv -n openshift-gitops-operator "$CSV_NAME" -o jsonpath='{.status.reason}')

                  echo "Waiting for Operator CSV to be ready: status='$CSV_STATUS' ($attempt/$MAX_RETRIES)"
                fi

                if (( attempt >= MAX_RETRIES )); then
                  echo "Timeout waiting for Operator to be ready after $((SLEEP * MAX_RETRIES)) seconds."
                  exit 1
                fi

                ((attempt++))
                sleep "$SLEEP"
              done

              echo "openshift-gitops-operator installed successfully!"
