apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
