apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: efs.csi.aws.com
  annotations:
spec:
  managementState: Managed
