apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: openshift-cluster-csi-drivers
  namespace: openshift-cluster-csi-drivers
spec:
  upgradeStrategy: Default
