apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: aws-efs-cloud-credentials
  namespace: openshift-cluster-csi-drivers
  annotations:
stringData:
  credentials: |-
    [default]
    sts_regional_endpoints = regional
    role_arn = {{ .Values.roleArn }}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
