apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: test-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: httpd-24
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: index-html
        - mountPath: /data-efs
          name: efs-test
        - mountPath: /data-gp3
          name: gp3-test
        - mountPath: /data-gp3-kms
          name: gp3-kms
        - mountPath: /data-io2-kms
          name: io2-kms
        #- mountPath: /data/test-app-secret
        #  name: test-app-secret
        #  readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: index-html
        name: index-html
      - name: efs-test
        persistentVolumeClaim:
          claimName: efs-test
      - name: gp3-test
        persistentVolumeClaim:
          claimName: gp3-test
      - name: gp3-kms
        persistentVolumeClaim:
          claimName: gp3-kms
      - name: io2-kms
        persistentVolumeClaim:
          claimName: io2-kms
      #- name: test-app-secret
      #  secret:
      #    defaultMode: 420
      #    secretName: test-app-secret
