apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-app-externalsecret
  namespace: test-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: test-app-secretstore
    kind: SecretStore
  target:
    name: test-app-secret # Name of the Kubernetes Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.awsSecretStore }}  # Name of the secret in AWS Secrets Manager this-cluster-cluster-credentials
      property: username # Key within the JSON of the AWS secret cluster-admin
