apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    velero.io/exclude-from-backup=true
  name: efs-test
  namespace: test-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-csi
  volumeMode: Filesystem