apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: io2-kms
  namespace: test-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: io2-csi-kms
  volumeMode: Filesystem