apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp3-kms
  namespace: test-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi-kms
  volumeMode: Filesystem