apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
    #eks.amazonaws.com/audience: <audience name>
  name: test-app
  namespace: test-app
