{{- range .Values.infrastructure }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .chart }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    chart: {{ .chart }}
    targetRevision: {{ .targetRevision }}
    helm:
      values: |
{{ toYaml .values | indent 8 }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
