{{- $infrastructure := .Values.infrastructure }}
{{- range $i, $app := $infrastructure }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.chart }}
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ $app.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: main
    path: charts/{{ $app.chart }}
    helm:
      values: |
{{ toYaml $app.values | indent 8 }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
