apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      http_config:
        proxy_from_environment: true
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
    receivers:
      - name: sns_receiver
        sns_configs:
          - send_resolved: false
            sigv4:
              region: {{ .Values.region }}
            #topic_arn: arn:aws:sns:ap-southeast-2:664418987929:one-rosa-monitoring-sns-topic
            topic_arn: {{ .Values.topicArn }}
            subject: 'Alert: {{ "{{" }} .GroupLabels.severity  | toUpper {{ "}}" }} - {{ "{{" }} .GroupLabels.alertname {{ "}}" }}'
    route:
      group_by:
        - namespace
        - alertname
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: sns_receiver
      routes:
        - matchers:
            - severity = critical
          receiver: sns_receiver
          group_wait: 10s
          group_interval: 2m
          repeat_interval: 1h
        - matchers:
            - severity = warning
          receiver: sns_receiver
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
        - matchers:
            - severity = info
          receiver: sns_receiver
          group_wait: 1m
          group_interval: 15m
          repeat_interval: 48h
