apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.27.0
  name: alertmanager-main
  namespace: openshift-monitoring
