kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: true
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: cert-manager
